POST http://localhost:8080/message/stream-topic-1
Content-Type: application/json

{
  "message": "test-topic-1"
}

###

POST http://localhost:8080/message/stream-topic-2
Content-Type: application/json

{
  "message": "test-topic-2"
}

###

POST http://localhost:8080/message/stream-topic-3
Content-Type: application/json

{
  "message": "test-topic-3"
}

###
