POST http://localhost:8080/message/streamTopic1
Content-Type: application/json

{
  "message": "test-topic-1"
}

###

POST http://localhost:8080/message/streamTopic2
Content-Type: application/json

{
  "message": "test-topic-2"
}

###

POST http://localhost:8080/message/streamTopic3
Content-Type: application/json

{
  "message": "test-topic-3"
}

###
