POST http://localhost:8080/message/streamsTopic1
Content-Type: application/json

{
  "message": "test-topic-1"
}

###

POST http://localhost:8080/message/streamsTopic2
Content-Type: application/json

{
  "message": "test-topic-2"
}

###

POST http://localhost:8080/message/streamsTopic3
Content-Type: application/json

{
  "message": "test-topic-3"
}

###
